version: "3"
services:
  php:
    build: .
    ports:
      - "8888:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - database

  database:
    image: mysql:8.4
    # CATATAN:
    # Mulai MySQL versi 8.1 ke atas, plugin autentikasi default sudah menggunakan 'caching_sha2_password'.
    # Jadi, Anda TIDAK PERLU menambahkan baris 'command' di bawah jika menggunakan MySQL 8.1 atau lebih baru.
    #
    # Namun, jika menggunakan MySQL versi 8.0 atau lebih lama, Anda perlu menambahkan baris berikut agar
    # MySQL menggunakan 'mysql_native_password' untuk autentikasi:
    #
    # Untuk MySQL versi 8.0 atau lebih lama, aktifkan baris berikut (hapus tanda '#' di depan 'command'):
    
    # command: --default-authentication-plugin=mysql_native_password

    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: docker_php
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - database

volumes:
  database: